version: "3.9"

services:
  ui:
    image: ${IMG_NODE}
    hostname: ${UI_HOST}
    ports:
      - ${UI_EXTERNAL_PORT}:${UI_PORT}
    environment:
      - PORT=${UI_PORT}
      - NODE_ENV=development
    working_dir: /app
    volumes:
      - '../services/ui/:/app'
    command: sh -c "npm install && npm run dev"
    networks:
      - nse
    labels:
      logging: "promtail"
      logging_jobname: "ui"

networks:
  nse:
    external: true
